### ISSUE TITLE
Implement "report post as spam/unwanted" feature.

### ISSUE THREAD

**Issue by Firesphere** [silverstripe-archive/silverstripe-forum#152]
It would be great to be able to report posts, so a moderator can review and optionally take action.

**Comment by Olliepop** [comment]
@edlinklater @camfindlay Feel free to assign me on this one if you feel it would be a good feature to implement

**Comment by edlinklater** [comment]
@Olliepop: Can only assign people with commit rights on the repo, but feel free to go ahead! :+1:
