### ISSUE TITLE
Move BBCodeParser to Forum

### ISSUE THREAD

**Issue by Firesphere** [silverstripe-archive/silverstripe-forum#191]
Either move the current BBCodeParser and DBText::Parse() method to the Forum module, as they're not required in core.

Other (in my opinion better) option, is to switch to Golanka/BBCodeParser. It's better maintained, not as old as the one in framework. And has friendlier parsing. Plus easy add codes.

**Comment by dhensby** [comment]
How about moving to markdown :P

**Comment by Firesphere** [comment]
That actually sounds like something that would make sense. But... which one? There doesn't seem to be a SilverStripe maintained one?

**Comment by dhensby** [comment]
Need to create one :)

https://github.com/erusev/parsedown is a good parser and is used on https://github.com/silverstripe/silverstripe-docsviewer

**Comment by camfindlay** [comment]
+1 for moving forum to markdown

**Comment by camfindlay** [comment]
Perhaps since some BBCode methods are being dep'd in 4 core, updating this module for 4 compat might make sense to do the markdown move at the same time? (might need a way to ensure old bbcode content in people's databases can be converted to MD too).

**Comment by DryerLintPurple** [comment]
As another option, how about s9e\TextFormatter? It looks to be one of the most popular on Packagist, and it supports both BBCode and Markdown, which would be a nice option. The dependency on a package called 'regexp-builder' makes me nervous, though. Hope somebody's doing some serious bad markup/XSS testing!

https://github.com/s9e/TextFormatter
https://packagist.org/packages/s9e/text-formatter
